"""
============================================================================
 LESSON 12: Supervised Fine-Tuning (SFT) — Turning Base LLMs into Assistants
============================================================================

 Goal: Understand every step required to turn a raw, pre-trained language
       model into an instruction-following chat assistant.

 Topics covered:
   1. Base vs Chat Models — Why raw LLMs don't follow instructions
   2. Instruction Datasets — Alpaca / ShareGPT format, creating samples
   3. Chat Templates — System / User / Assistant roles
   4. SFT Training — Cross-entropy loss only on assistant tokens
   5. LoRA — Low-Rank Adaptation from scratch
   6. QLoRA Concept — Quantize base model + LoRA on top

 Every section has:
   - A short explanation (read the docstrings)
   - Working code you can run and modify
   - Exercises at the bottom

 Prerequisites: Lesson 8 (pre-training), Lesson 11 (evaluation)
============================================================================
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(42)


# ═══════════════════════════════════════════════════════════════════════════
# PART 1 — BASE vs CHAT MODELS
# ═══════════════════════════════════════════════════════════════════════════
#
# A base model (GPT, LLaMA-base) is trained with next-token prediction on
# raw internet text.  It's a *completion engine*, not a chat assistant.
#
# Ask it "What is the capital of France?" and it might continue with
# ten more quiz questions, because that's what similar text looked like
# in its training data.
#
# SFT teaches the model a new pattern: given an instruction, produce a
# helpful answer — not just a likely continuation.
# ═══════════════════════════════════════════════════════════════════════════

print("=" * 72)
print("PART 1: BASE vs CHAT MODELS")
print("=" * 72)


"""
WHY THIS MATTERS:
Without SFT, a base model is useless as an assistant.  It completes text
but doesn't follow instructions.  ChatGPT = GPT-base + SFT + RLHF.
The SFT step is what gives the model its "personality" and ability to
follow user requests.
"""

# Simulate a tiny "base model" that learned token co-occurrence patterns
vocab = ["What", "is", "the", "capital", "of", "France", "?",
         "Paris", "London", "Berlin", ".", "Who", "wrote", "How"]
vocab_size = len(vocab)
word2id = {w: i for i, w in enumerate(vocab)}

torch.manual_seed(42)
base_logits = torch.randn(vocab_size)  # random logits for next token

# A base model just picks whatever token is most probable in context.
# It doesn't "know" it should answer — it just continues the text.
base_probs = F.softmax(base_logits, dim=-1)
base_top5 = torch.topk(base_probs, 5)

print("\nPrompt: 'What is the capital of France?'")
print("\nBase model next-token predictions (no SFT):")
for prob, idx in zip(base_top5.values, base_top5.indices):
    print(f"  {vocab[idx]:>10s}  {prob:.4f}")
print("  → Base model just continues text — might output 'Who', 'How', etc.")

# After SFT, the model learns to produce the answer token
sft_logits = base_logits.clone()
sft_logits[word2id["Paris"]] = 5.0     # SFT boosts the correct answer
sft_logits[word2id["Who"]] = -2.0      # suppresses continuation patterns
sft_logits[word2id["How"]] = -2.0

sft_probs = F.softmax(sft_logits, dim=-1)
sft_top5 = torch.topk(sft_probs, 5)

print("\nAfter SFT — model learns to answer:")
for prob, idx in zip(sft_top5.values, sft_top5.indices):
    print(f"  {vocab[idx]:>10s}  {prob:.4f}")
print("  → SFT teaches: instruction in → helpful answer out.")

# The key difference in numbers
print(f"\nP('Paris' | base):  {base_probs[word2id['Paris']]:.4f}")
print(f"P('Paris' | SFT):   {sft_probs[word2id['Paris']]:.4f}")
print(f"Boost factor: {sft_probs[word2id['Paris']] / base_probs[word2id['Paris']]:.1f}x")


# ═══════════════════════════════════════════════════════════════════════════
# PART 2 — INSTRUCTION DATASETS
# ═══════════════════════════════════════════════════════════════════════════
#
# SFT requires (instruction, response) pairs — thousands to hundreds of
# thousands of them.  Two dominant formats:
#
# 1. Alpaca format:  {"instruction": ..., "input": ..., "output": ...}
#    - 52k examples, generated by GPT-3.5
#    - Simple single-turn tasks
#
# 2. ShareGPT format:  {"conversations": [{"from": "human", ...}, ...]}
#    - Multi-turn conversations scraped from ChatGPT
#    - More natural dialogue patterns
#
# The quality of your SFT data has more impact than its quantity.
# 1,000 high-quality examples often beat 100,000 noisy ones.
# ═══════════════════════════════════════════════════════════════════════════

print("\n" + "=" * 72)
print("PART 2: INSTRUCTION DATASETS")
print("=" * 72)

"""
WHY THIS MATTERS:
The SFT dataset IS the behavior specification for your assistant.
Every (instruction, response) pair teaches one pattern.  Get the data
right and a 7B model can rival a 70B model on specific tasks.
"""

# --- 2.1 Alpaca format examples -------------------------------------------

alpaca_examples = [
    {
        "instruction": "Translate the following sentence to French.",
        "input": "The weather is nice today.",
        "output": "Le temps est beau aujourd'hui."
    },
    {
        "instruction": "Summarize the main idea in one sentence.",
        "input": "Photosynthesis is the process by which plants convert "
                 "sunlight into chemical energy, producing oxygen as a "
                 "byproduct. This process is essential for life on Earth.",
        "output": "Plants convert sunlight into energy through photosynthesis, "
                  "producing oxygen essential for life."
    },
    {
        "instruction": "Write a Python function that checks if a number is prime.",
        "input": "",
        "output": "def is_prime(n):\n    if n < 2:\n        return False\n"
                  "    for i in range(2, int(n**0.5) + 1):\n"
                  "        if n % i == 0:\n            return False\n"
                  "    return True"
    },
]

print("\n--- Alpaca Format ---")
for i, ex in enumerate(alpaca_examples):
    inp_preview = ex["input"][:40] + "..." if len(ex["input"]) > 40 else ex["input"]
    out_preview = ex["output"][:40] + "..." if len(ex["output"]) > 40 else ex["output"]
    print(f"\n  Example {i+1}:")
    print(f"    instruction: {ex['instruction']}")
    print(f"    input:       {inp_preview if inp_preview else '(none)'}")
    print(f"    output:      {out_preview}")


# --- 2.2 ShareGPT format examples -----------------------------------------

sharegpt_examples = [
    {
        "conversations": [
            {"from": "human", "value": "What is gradient descent?"},
            {"from": "gpt", "value": "Gradient descent is an optimization "
             "algorithm that iteratively adjusts parameters by moving in "
             "the direction of steepest decrease of the loss function."},
            {"from": "human", "value": "What's the learning rate?"},
            {"from": "gpt", "value": "The learning rate controls the step "
             "size. Too large and you overshoot; too small and training "
             "is painfully slow. Typical values: 1e-5 to 1e-3 for SFT."},
        ]
    },
]

print("\n\n--- ShareGPT Format (multi-turn) ---")
for conv in sharegpt_examples[0]["conversations"]:
    role = "User" if conv["from"] == "human" else "Assistant"
    preview = conv["value"][:60] + "..." if len(conv["value"]) > 60 else conv["value"]
    print(f"  [{role:>9s}] {preview}")


# --- 2.3 Dataset statistics -----------------------------------------------

print("\n\n--- Common SFT Datasets ---")
datasets_info = [
    ("Alpaca",       "52K",    "Single-turn, GPT-3.5 generated"),
    ("ShareGPT",     "90K+",   "Multi-turn, real ChatGPT conversations"),
    ("FLAN v2",      "1.8M",   "1,800+ tasks, academic, very diverse"),
    ("OpenAssistant", "161K",  "Multi-turn, human-written, multilingual"),
    ("Dolly",        "15K",    "Single-turn, human-written by Databricks"),
    ("WizardLM",     "250K",   "Evolved instructions for complexity"),
]

print(f"  {'Dataset':<15s} {'Size':<8s} Description")
print(f"  {'─'*15:<15s} {'─'*8:<8s} {'─'*42}")
for name, size, desc in datasets_info:
    print(f"  {name:<15s} {size:<8s} {desc}")


# ═══════════════════════════════════════════════════════════════════════════
# PART 3 — CHAT TEMPLATES
# ═══════════════════════════════════════════════════════════════════════════
#
# Raw text needs structure.  Chat templates define how to pack system
# messages, user inputs, and assistant responses into a single token
# sequence the model can learn from.
#
# Different model families use different templates:
#   - ChatML:  <|im_start|>role\n...<|im_end|>
#   - LLaMA:   <s>[INST] ... [/INST]
#   - Alpaca:  ### Instruction:\n...\n### Response:\n
#
# The model never "sees" roles natively — it just sees tokens.
# The template is how we ENCODE role information into the token stream.
# ═══════════════════════════════════════════════════════════════════════════

print("\n" + "=" * 72)
print("PART 3: CHAT TEMPLATES")
print("=" * 72)

"""
WHY THIS MATTERS:
If you use the wrong template at inference time (different from training),
the model won't know where instructions end and answers begin.  Template
mismatch is the #1 cause of fine-tuned models "not working."
"""


# --- 3.1 ChatML format (used by Qwen, Yi, many others) --------------------

def format_chatml(messages):
    """Format messages using ChatML template."""
    formatted = ""
    for msg in messages:
        formatted += f"<|im_start|>{msg['role']}\n{msg['content']}<|im_end|>\n"
    formatted += "<|im_start|>assistant\n"
    return formatted


# --- 3.2 LLaMA-2 chat format ----------------------------------------------

def format_llama2(messages):
    """Format messages using LLaMA-2 chat template."""
    system_msg = ""
    formatted = "<s>"
    for msg in messages:
        if msg["role"] == "system":
            system_msg = msg["content"]
        elif msg["role"] == "user":
            if system_msg:
                formatted += f"[INST] <<SYS>>\n{system_msg}\n<</SYS>>\n\n{msg['content']} [/INST]"
                system_msg = ""
            else:
                formatted += f"[INST] {msg['content']} [/INST]"
        elif msg["role"] == "assistant":
            formatted += f" {msg['content']} </s><s>"
    return formatted


# --- 3.3 Simple Alpaca format (no special tokens needed) -------------------

def format_alpaca(instruction, input_text="", output_text=""):
    """Format using Alpaca template."""
    if input_text:
        prompt = (f"Below is an instruction that describes a task, paired "
                  f"with further context.\n\n"
                  f"### Instruction:\n{instruction}\n\n"
                  f"### Input:\n{input_text}\n\n"
                  f"### Response:\n")
    else:
        prompt = (f"Below is an instruction that describes a task.\n\n"
                  f"### Instruction:\n{instruction}\n\n"
                  f"### Response:\n")
    if output_text:
        prompt += output_text
    return prompt


# --- 3.4 Demo: same conversation, three templates -------------------------

conversation = [
    {"role": "system", "content": "You are a helpful coding assistant."},
    {"role": "user", "content": "Write a hello world in Python."},
]

print("\n--- ChatML Template ---")
print(format_chatml(conversation))

print("--- LLaMA-2 Template ---")
print(format_llama2(conversation))

print("--- Alpaca Template ---")
print(format_alpaca(
    instruction="Write a hello world in Python.",
    output_text='print("Hello, World!")',
))


# --- 3.5 Tokenization of a chat: role boundaries --------------------------

print("\n--- Token Roles (what the model actually sees) ---")

# Simulate tokenization with role labels
tokens =       ["<|im_start|>", "system", "\\n", "You", "are", "helpful", ".", "<|im_end|>",
                 "<|im_start|>", "user", "\\n", "Hello", "!", "<|im_end|>",
                 "<|im_start|>", "assistant", "\\n", "Hi", "there", "!", "<|im_end|>"]
role_labels = ["special",      "system", "system", "system", "system", "system", "system", "special",
               "special",      "user",   "user",  "user",  "user", "special",
               "special",      "assistant", "assistant", "assistant", "assistant", "assistant", "special"]

print(f"  {'Token':<18s} Role")
print(f"  {'─'*18:<18s} {'─'*12}")
for tok, role in zip(tokens, role_labels):
    marker = "  ←  TRAIN ON THIS" if role == "assistant" else ""
    print(f"  {tok:<18s} {role:<12s}{marker}")

print("\n  Key insight: SFT loss is computed ONLY on assistant tokens.")
print("  System and user tokens provide context but don't contribute to loss.")


# ═══════════════════════════════════════════════════════════════════════════
# PART 4 — SFT TRAINING (loss masking)
# ═══════════════════════════════════════════════════════════════════════════
#
# SFT uses the exact same cross-entropy loss as pre-training, but with
# a critical difference: we MASK the loss on non-assistant tokens.
#
# Why?  We don't want the model to learn to predict system prompts or
# user messages.  We only want it to learn: "given this context, produce
# THIS assistant response."
#
# Implementation: set loss labels to -100 for tokens we want to ignore.
# PyTorch's CrossEntropyLoss ignores targets with value -100.
# ═══════════════════════════════════════════════════════════════════════════

print("\n" + "=" * 72)
print("PART 4: SFT TRAINING — Loss Masking on Assistant Tokens")
print("=" * 72)

torch.manual_seed(42)

"""
WHY THIS MATTERS:
If you train on ALL tokens (including system/user), the model wastes
capacity learning to mimic user questions.  Masking ensures every
gradient update pushes the model toward better RESPONSES only.
This is the single most important implementation detail in SFT.
"""


# --- 4.1 Build a toy SFT example -----------------------------------------

IGNORE_INDEX = -100
vocab_size = 32
seq_len = 20

# Simulate token IDs for a conversation
token_ids = torch.randint(0, vocab_size, (seq_len,))

# Mark which positions are assistant tokens (1 = assistant, 0 = other)
# Positions 0-7: system/user prompt, 8-14: assistant response, 15-19: padding
is_assistant = torch.zeros(seq_len, dtype=torch.bool)
is_assistant[8:15] = True   # only assistant response positions

# Build labels: shift by 1 (predict next token), mask non-assistant
labels = torch.full((seq_len,), IGNORE_INDEX, dtype=torch.long)
labels[8:15] = token_ids[9:16]  # next-token targets for assistant positions

print(f"\nToken IDs:     {token_ids.tolist()}")
print(f"Is assistant:  {is_assistant.int().tolist()}")
print(f"Labels:        {labels.tolist()}")
print(f"  -100 = masked (no loss), other = target token ID")
print(f"  {(labels != IGNORE_INDEX).sum().item()} out of {seq_len} tokens contribute to loss")


# --- 4.2 SFT loss computation with masking --------------------------------

class TinySFTModel(nn.Module):
    """Minimal model to demonstrate SFT loss masking."""

    def __init__(self, vocab_size, d_model=64):
        super().__init__()
        self.embed = nn.Embedding(vocab_size, d_model)
        self.head = nn.Linear(d_model, vocab_size)

    def forward(self, input_ids):
        return self.head(self.embed(input_ids))


model = TinySFTModel(vocab_size)
logits = model(token_ids.unsqueeze(0)).squeeze(0)  # (seq_len, vocab_size)

# Standard cross-entropy ignores targets == -100
loss_fn = nn.CrossEntropyLoss(ignore_index=IGNORE_INDEX)
sft_loss = loss_fn(logits, labels)

# Compare with naive loss on ALL tokens (wrong approach)
naive_labels = token_ids[1:].clone()  # next-token for every position
naive_labels = F.pad(naive_labels, (0, 1), value=0)
naive_loss = loss_fn(logits, naive_labels)

print(f"\nSFT loss (assistant only):  {sft_loss.item():.4f}")
print(f"Naive loss (all tokens):    {naive_loss.item():.4f}")
print(f"  → SFT focuses gradients on what matters: the response quality.")


# --- 4.3 Full SFT training loop ------------------------------------------

torch.manual_seed(42)
model = TinySFTModel(vocab_size)
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3)

# Create a mini SFT "dataset" — 8 conversation samples
batch_size = 8
input_batch = torch.randint(0, vocab_size, (batch_size, seq_len))
label_batch = torch.full((batch_size, seq_len), IGNORE_INDEX, dtype=torch.long)

# For each sample, mark positions 8-14 as assistant (same pattern)
for i in range(batch_size):
    label_batch[i, 8:15] = input_batch[i, 9:16]

print(f"\n--- SFT Training Loop ---")
print(f"Batch: {batch_size} samples × {seq_len} tokens")
print(f"Assistant tokens per sample: 7")
print(f"Total trainable tokens per batch: {batch_size * 7}")

num_steps = 100
for step in range(num_steps):
    logits = model(input_batch)                              # (B, T, V)
    loss = loss_fn(logits.view(-1, vocab_size), label_batch.view(-1))
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

    if step % 20 == 0 or step == num_steps - 1:
        print(f"  Step {step:3d} | Loss: {loss.item():.4f} | "
              f"PPL: {torch.exp(loss).item():.1f}")

print(f"\n  Started at PPL ≈ {vocab_size} (random over {vocab_size} tokens)")
print(f"  → Loss drops = model learns assistant response patterns.")


# ═══════════════════════════════════════════════════════════════════════════
# PART 5 — LoRA (Low-Rank Adaptation) FROM SCRATCH
# ═══════════════════════════════════════════════════════════════════════════
#
# Full fine-tuning updates ALL parameters.  For a 7B model that's 14 GB
# of gradients + 56 GB of optimizer states = too much memory.
#
# LoRA's insight: the weight UPDATE during fine-tuning is low-rank.
# Instead of updating W directly, learn two small matrices A and B:
#
#     W' = W + (B @ A)    where W is (d, d), A is (d, r), B is (r, d)
#                          r << d  (e.g., r=16 vs d=4096)
#
# Initialization:
#   - A: random normal (so gradients flow from the start)
#   - B: zeros (so W' = W at initialization — no disruption)
#
# Only A and B are trained.  W is frozen.
# ═══════════════════════════════════════════════════════════════════════════

print("\n" + "=" * 72)
print("PART 5: LoRA — Low-Rank Adaptation FROM SCRATCH")
print("=" * 72)

torch.manual_seed(42)

"""
WHY THIS MATTERS:
LoRA made fine-tuning accessible.  Before LoRA, fine-tuning a 7B model
required 80+ GB of GPU memory.  With LoRA (rank=16), you need < 16 GB.
It's the standard approach for customizing LLMs today.
"""


# --- 5.1 LoRA layer implementation ----------------------------------------

class LoRALinear(nn.Module):
    """
    Wraps an existing nn.Linear with Low-Rank Adaptation.

    Forward:  y = W @ x + (B @ A) @ x * (alpha / r)

    W is frozen.  Only A and B are trainable.
    alpha/r is a scaling factor to control the magnitude of the adaptation.
    """

    def __init__(self, base_linear: nn.Linear, rank: int = 16, alpha: float = 16.0):
        super().__init__()
        self.base = base_linear
        self.rank = rank
        self.alpha = alpha

        in_features = base_linear.in_features
        out_features = base_linear.out_features

        # A: (rank, in_features) — initialized with random normal
        self.lora_A = nn.Parameter(torch.randn(rank, in_features) * 0.01)
        # B: (out_features, rank) — initialized with zeros
        self.lora_B = nn.Parameter(torch.zeros(out_features, rank))

        # Freeze the base weights
        self.base.weight.requires_grad = False
        if self.base.bias is not None:
            self.base.bias.requires_grad = False

    def forward(self, x):
        base_out = self.base(x)
        # LoRA path: x @ A^T @ B^T  (equivalent to (B @ A) @ x)
        lora_out = (x @ self.lora_A.T) @ self.lora_B.T
        scaling = self.alpha / self.rank
        return base_out + lora_out * scaling


# --- 5.2 Verify zero-init means no disruption ----------------------------

d_model = 256
base_linear = nn.Linear(d_model, d_model)
lora_layer = LoRALinear(base_linear, rank=16, alpha=16.0)

x = torch.randn(2, 10, d_model)  # (batch, seq_len, d_model)
base_out = base_linear(x)
lora_out = lora_layer(x)

diff = (base_out - lora_out).abs().max().item()
print(f"\nMax difference at init (should be 0): {diff:.10f}")
print(f"  → B is zeros, so B @ A = 0.  LoRA starts as identity adapter.")


# --- 5.3 Parameter savings -----------------------------------------------

print(f"\n--- Parameter Savings ---")

original_params = d_model * d_model
print(f"Original Linear({d_model}, {d_model}): {original_params:,} params")

for rank in [4, 8, 16, 32, 64]:
    lora_params = rank * d_model + d_model * rank  # A + B
    ratio = lora_params / original_params * 100
    print(f"  LoRA rank={rank:2d}: {lora_params:>8,} params ({ratio:5.2f}% of original)")


# --- 5.4 Scaling to real models -------------------------------------------

print(f"\n--- LoRA on a 7B Model (LLaMA-2 7B) ---")

d = 4096
n_layers = 32
n_targets = 4    # Q, K, V, O projections in each layer

total_model = 7_000_000_000
full_ft_trainable = total_model

for rank in [8, 16, 32, 64]:
    lora_per_target = rank * d + d * rank   # A + B for one Linear
    total_lora = lora_per_target * n_targets * n_layers
    pct = total_lora / total_model * 100

    full_ft_mem = full_ft_trainable * 2 / 1e9      # FP16 params
    full_ft_opt = full_ft_trainable * (4 + 4) / 1e9  # Adam: momentum + variance
    lora_opt = total_lora * (4 + 4) / 1e9

    print(f"\n  Rank {rank:2d}:")
    print(f"    Trainable:    {total_lora:>12,} ({pct:.2f}% of 7B)")
    print(f"    LoRA memory:  {total_lora * 2 / 1e9:.2f} GB (params in FP16)")
    print(f"    Optimizer:    {lora_opt:.2f} GB (vs {full_ft_opt:.1f} GB for full FT)")


# --- 5.5 Training a LoRA model -------------------------------------------

print(f"\n--- Training LoRA vs Full Fine-Tune ---")
torch.manual_seed(42)

d_model = 128
num_classes = 10
batch_size = 32
seq_len = 16

# Pretrained base: a simple 2-layer transformer-ish model
class TinyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.embed = nn.Embedding(100, d_model)
        self.attn_proj = nn.Linear(d_model, d_model)
        self.ffn1 = nn.Linear(d_model, d_model * 4)
        self.ffn2 = nn.Linear(d_model * 4, d_model)
        self.head = nn.Linear(d_model, num_classes)

    def forward(self, x):
        h = self.embed(x)
        h = h + F.gelu(self.attn_proj(h))
        h = h + self.ffn2(F.gelu(self.ffn1(h)))
        return self.head(h.mean(dim=1))


# Synthetic dataset
input_ids = torch.randint(0, 100, (batch_size, seq_len))
targets = torch.randint(0, num_classes, (batch_size,))

# Full fine-tune
model_full = TinyModel()
opt_full = torch.optim.AdamW(model_full.parameters(), lr=1e-3)
loss_fn = nn.CrossEntropyLoss()

# LoRA fine-tune (only adapt attn_proj and ffn1)
model_lora = TinyModel()
model_lora.load_state_dict(model_full.state_dict())
model_lora.attn_proj = LoRALinear(model_lora.attn_proj, rank=8)
model_lora.ffn1 = LoRALinear(model_lora.ffn1, rank=8)
# Freeze everything except LoRA parameters
for name, param in model_lora.named_parameters():
    if "lora_" not in name:
        param.requires_grad = False
opt_lora = torch.optim.AdamW(
    [p for p in model_lora.parameters() if p.requires_grad], lr=1e-3
)

full_trainable = sum(p.numel() for p in model_full.parameters() if p.requires_grad)
lora_trainable = sum(p.numel() for p in model_lora.parameters() if p.requires_grad)
print(f"\nFull FT trainable: {full_trainable:,} params")
print(f"LoRA trainable:    {lora_trainable:,} params ({lora_trainable/full_trainable*100:.1f}%)")

print(f"\n  {'Step':>4s}  {'Full FT Loss':>13s}  {'LoRA Loss':>10s}")
print(f"  {'─'*4:>4s}  {'─'*13:>13s}  {'─'*10:>10s}")

for step in range(60):
    # Full FT step
    logits_f = model_full(input_ids)
    loss_f = loss_fn(logits_f, targets)
    loss_f.backward()
    opt_full.step()
    opt_full.zero_grad()

    # LoRA step
    logits_l = model_lora(input_ids)
    loss_l = loss_fn(logits_l, targets)
    loss_l.backward()
    opt_lora.step()
    opt_lora.zero_grad()

    if step % 10 == 0 or step == 59:
        print(f"  {step:4d}  {loss_f.item():13.4f}  {loss_l.item():10.4f}")

print(f"\n  → LoRA trains {full_trainable/lora_trainable:.0f}x fewer params but converges comparably!")


# ═══════════════════════════════════════════════════════════════════════════
# PART 6 — QLoRA CONCEPT
# ═══════════════════════════════════════════════════════════════════════════
#
# QLoRA = Quantized base weights + LoRA adapters on top.
#
# The idea: since we freeze the base weights anyway, why store them in
# FP16?  Quantize to 4-bit (NF4) → 4× memory savings on the frozen part.
# LoRA adapters stay in FP16/BF16 for training stability.
#
# This is how you fine-tune a 65B model on a single 48 GB GPU.
# ═══════════════════════════════════════════════════════════════════════════

print("\n" + "=" * 72)
print("PART 6: QLoRA — Quantized Base + LoRA")
print("=" * 72)

"""
WHY THIS MATTERS:
QLoRA democratized LLM fine-tuning.  Before QLoRA, fine-tuning LLaMA-65B
required 8× A100 80GB GPUs (~$200/hr on cloud).  With QLoRA you can do
it on a single 48GB GPU (~$4/hr).  50× cost reduction.
"""


# --- 6.1 Quantization basics (simulated) ---------------------------------

print(f"\n--- Quantization: FP16 → INT4 ---")

# Simulate quantization of a weight tensor
torch.manual_seed(42)
W = torch.randn(256, 256)  # pretend this is a model weight

# FP32 baseline
fp32_bytes = W.numel() * 4
fp16_bytes = W.numel() * 2
int8_bytes = W.numel() * 1
int4_bytes = W.numel() * 0.5  # 4 bits = 0.5 bytes

print(f"Weight shape: {W.shape}")
print(f"  FP32: {fp32_bytes:>10,} bytes ({fp32_bytes / 1024:.1f} KB)")
print(f"  FP16: {fp16_bytes:>10,} bytes ({fp16_bytes / 1024:.1f} KB)")
print(f"  INT8: {int8_bytes:>10,} bytes ({int8_bytes / 1024:.1f} KB)")
print(f"  INT4: {int4_bytes:>10,.0f} bytes ({int4_bytes / 1024:.1f} KB)")

# Simulate absmax quantization to INT8
scale = W.abs().max()
W_int8 = torch.round(W / scale * 127).clamp(-128, 127).to(torch.int8)
W_deq = W_int8.float() / 127 * scale
quant_error = (W - W_deq).abs().mean().item()

print(f"\n  Absmax INT8 quantization error: {quant_error:.6f}")
print(f"  Original weight range: [{W.min():.4f}, {W.max():.4f}]")
print(f"  Dequantized range:     [{W_deq.min():.4f}, {W_deq.max():.4f}]")


# --- 6.2 QLoRA memory math -----------------------------------------------

print(f"\n--- QLoRA Memory Budget (7B Model) ---")

params_7b = 7_000_000_000

# Approach 1: Full fine-tuning in FP16
full_ft_params = params_7b * 2 / 1e9       # FP16 weights
full_ft_grads  = params_7b * 2 / 1e9       # FP16 gradients
full_ft_adam   = params_7b * (4 + 4) / 1e9  # FP32 momentum + variance
full_ft_total  = full_ft_params + full_ft_grads + full_ft_adam

print(f"\n  Full Fine-Tune (FP16):")
print(f"    Parameters:  {full_ft_params:5.1f} GB")
print(f"    Gradients:   {full_ft_grads:5.1f} GB")
print(f"    Adam states: {full_ft_adam:5.1f} GB")
print(f"    ────────────────────────")
print(f"    TOTAL:       {full_ft_total:5.1f} GB  ← Needs 2× A100 80GB")

# Approach 2: LoRA in FP16
rank = 16
lora_params_count = rank * 4096 * 2 * 4 * 32  # rank × d × 2 × n_targets × n_layers
lora_base    = params_7b * 2 / 1e9
lora_adapter = lora_params_count * 2 / 1e9
lora_grads   = lora_params_count * 2 / 1e9
lora_adam    = lora_params_count * (4 + 4) / 1e9
lora_total   = lora_base + lora_adapter + lora_grads + lora_adam

print(f"\n  LoRA (rank=16, FP16 base):")
print(f"    Base (frozen):  {lora_base:5.1f} GB")
print(f"    LoRA adapters:  {lora_adapter:5.3f} GB")
print(f"    LoRA gradients: {lora_grads:5.3f} GB")
print(f"    LoRA Adam:      {lora_adam:5.3f} GB")
print(f"    ────────────────────────")
print(f"    TOTAL:          {lora_total:5.1f} GB  ← Fits 1× A100 80GB")

# Approach 3: QLoRA (4-bit base + LoRA)
qlora_base   = params_7b * 0.5 / 1e9       # 4-bit = 0.5 bytes
qlora_adapter = lora_adapter
qlora_grads  = lora_grads
qlora_adam   = lora_adam
qlora_total  = qlora_base + qlora_adapter + qlora_grads + qlora_adam

print(f"\n  QLoRA (4-bit base + LoRA rank=16):")
print(f"    Base (4-bit):   {qlora_base:5.1f} GB  ← 4× smaller!")
print(f"    LoRA adapters:  {qlora_adapter:5.3f} GB")
print(f"    LoRA gradients: {qlora_grads:5.3f} GB")
print(f"    LoRA Adam:      {qlora_adam:5.3f} GB")
print(f"    ────────────────────────")
print(f"    TOTAL:          {qlora_total:5.1f} GB  ← Fits consumer GPU!")

print(f"\n  Memory savings:")
print(f"    Full FT → LoRA:  {full_ft_total/lora_total:.1f}× reduction")
print(f"    Full FT → QLoRA: {full_ft_total/qlora_total:.1f}× reduction")
print(f"    LoRA → QLoRA:    {lora_total/qlora_total:.1f}× reduction")


# --- 6.3 QLoRA key innovations -------------------------------------------

print(f"\n--- QLoRA Key Innovations ---")
print(f"""
  1. NF4 (Normal Float 4-bit)
     - Quantization levels are spaced for normal distributions
     - Neural network weights ARE approximately normal
     - Better than uniform INT4 for model weights

  2. Double Quantization
     - Quantize the quantization constants themselves
     - Saves ~0.4 bits per parameter (small but it adds up)

  3. Paged Optimizers
     - Offload optimizer states to CPU when GPU OOM
     - Automatic, transparent paging (like virtual memory)
     - Handles memory spikes during gradient checkpointing

  4. Training Recipe
     - Base weights: NF4 quantized (frozen)
     - LoRA adapters: BF16 (trainable)
     - Forward: dequantize on-the-fly for matmul
     - Backward: gradients flow through dequantized weights to LoRA
""")


# --- 6.4 Comparison table ------------------------------------------------

print(f"--- Method Comparison ---")
print(f"  {'Method':<20s} {'Trainable':<15s} {'GPU Memory':<12s} {'Quality':<10s}")
print(f"  {'─'*20:<20s} {'─'*15:<15s} {'─'*12:<12s} {'─'*10:<10s}")
print(f"  {'Full Fine-Tune':<20s} {'100%':<15s} {'~112 GB':<12s} {'Best':<10s}")
print(f"  {'LoRA (r=16)':<20s} {'0.1-0.5%':<15s} {'~16 GB':<12s} {'Very good':<10s}")
print(f"  {'QLoRA (r=16)':<20s} {'0.1-0.5%':<15s} {'~6 GB':<12s} {'Good':<10s}")
print(f"  {'Prompt Tuning':<20s} {'<0.01%':<15s} {'~14 GB':<12s} {'Limited':<10s}")


# ═══════════════════════════════════════════════════════════════════════════
# EXERCISES
# ═══════════════════════════════════════════════════════════════════════════

print("\n" + "=" * 72)
print("EXERCISES")
print("=" * 72)
print("""
Exercise 1: Format an Instruction Dataset
-------------------------------------------
Create 5 instruction-response pairs in Alpaca format.
  a) Write a format_to_chatml() function that converts Alpaca format
     {"instruction", "input", "output"} into ChatML template tokens.
  b) Handle both cases: with and without "input" field.
  c) Verify your output looks like:
     <|im_start|>user
     Instruction + Input
     <|im_end|>
     <|im_start|>assistant
     Output
     <|im_end|>

Exercise 2: Implement SFT Loss Masking
----------------------------------------
Given a batch of token_ids and a list marking assistant token positions:
  a) Build the labels tensor (next-token targets for assistant,
     -100 for everything else).
  b) Compute cross-entropy loss, confirming loss is only over assistant tokens.
  c) Verify: change a non-assistant token ID and confirm the loss
     does NOT change (because those tokens are masked).

Exercise 3: LoRA Merge
-----------------------
After LoRA training, you can MERGE the adapters back into the base weights
for inference (no overhead at serving time):
  W_merged = W + (B @ A) * (alpha / rank)
  a) Given a trained LoRALinear, compute W_merged.
  b) Create a standard nn.Linear with W_merged as its weight.
  c) Verify: merged_linear(x) == lora_layer(x) for any input x
     (should match to floating-point precision, ~1e-6).

Exercise 4: Rank Sensitivity Experiment
-----------------------------------------
Using the TinyModel from Part 5:
  a) Train with LoRA ranks [2, 4, 8, 16, 32, 64, 128].
  b) For each rank, record final loss after 100 steps.
  c) Plot (text-based) rank vs final loss.
  d) Find the "sweet spot" — smallest rank that still converges well.
  e) Compute parameter count for each rank.
     When does LoRA approach full fine-tuning in parameter count?

Exercise 5: Multi-Turn SFT Data
---------------------------------
Create a multi-turn conversation (3+ turns) in ShareGPT format.
  a) Convert it to ChatML template.
  b) Build the label mask: -100 for system/user tokens,
     real targets for ALL assistant turns (not just the last one).
  c) Compute total masked vs unmasked tokens.
  d) Why is it important to train on ALL assistant turns, not just
     the final one? (Hint: think about what the model needs to learn
     for multi-turn conversations.)
""")
